/**
 * All unique skill names from job templates (English keys for matching).
 * Used for searchable skills dropdown in candidate flow and employer post.
 * Must match keys in messages skillNames (en/ka) and skills in entry_level_jobs_300.csv.
 */
export const ALL_SKILLS = [
  "Accuracy",
  "Active listening",
  "Analytical thinking",
  "Analytics basics",
  "Attention to detail",
  "Basic SQL",
  "Basic accounting",
  "Basic design tools",
  "Basic machine handling",
  "Basic math",
  "Basic record-keeping",
  "CRM tools",
  "Calm under pressure",
  "Cash handling",
  "Child safety",
  "Cleanliness",
  "Coffee preparation",
  "Communication",
  "Confidentiality",
  "Conflict resolution",
  "Content planning",
  "Copywriting",
  "Creativity",
  "Customer service",
  "Data accuracy",
  "Data entry",
  "Document management",
  "Documentation",
  "Email etiquette",
  "Empathy",
  "Excel",
  "Excel basics",
  "Following instructions",
  "Following procedures",
  "Food safety",
  "Hygiene",
  "Incident reporting",
  "Inventory handling",
  "Learning mindset",
  "MS Office",
  "Manual dexterity",
  "Multitasking",
  "Navigation",
  "Numeracy",
  "Observation",
  "Organization",
  "POS systems",
  "Packing",
  "Patience",
  "Phone etiquette",
  "Physical stamina",
  "Problem solving",
  "Product knowledge",
  "Product placement",
  "Quality checks",
  "Reconciliation",
  "Reliability",
  "Responsibility",
  "Safe driving",
  "Safety awareness",
  "Safety procedures",
  "Scheduling",
  "Speed",
  "Speed & accuracy",
  "Social media",
  "Stress tolerance",
  "Teamwork",
  "Time management",
  "Typing",
  "Upselling",
  "Vigilance",
  "Written communication",
  "Flexibility",
  "Computer basics",
].sort();
